version: '3'

services:
  test:
    image: test:latest
    # add any additional configuration options for the test service here

  test2:
    image: test2:latest
    # add any additional configuration options for the test2 service here
